// frontend/src/components/AppClock.vue
<script setup lang="ts">
import { useNow } from '@vueuse/core'
import { format } from 'date-fns'

const now = $(useNow({ interval: 1000 }))
const value = $computed(() => format(now, 'do MMMM, yyyy hh:mm:ss a'))
</script>

<template>
  <p class="clock">{{ value }}</p>
</template>

<style scoped>
.clock {
  font-weight: 600;
}
</style>

// src/lib/AppClock.svelte
<script lang="ts">
	import { format } from 'date-fns';
	import { getContext } from 'svelte';
	import type { Readable } from 'svelte/store';

	const time = getContext('time') as Readable<Date>;
	$: value = format($time, 'do MMMM, yyyy hh:mm:ss a');
</script>

<p class="clock">{value}</p>

<style>
	.clock {
		font-weight: 600;
	}
</style>
